VitrineCV/Models/ErrorViewModel.cs
using System;

namespace VitrineCV.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VitrineCV/Models/Formation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VitrineCV.Models
{
    public class Formation
    {
        public int ID { get; set; }
        public string Organisme { get; set; }
        public string Intitule { get; set; }
        public string Annee { get; set; }
        public string Ville { get; set; }
        public string Specialisation { get; set; }
    }
}

VitrineCV/Controllers/CVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VitrineCV.Data;
using VitrineCV.Models;

namespace VitrineCV.Controllers
{
    public class CVController : Controller
    {
        //private readonly CVContext _context;

        //public CVController(CVContext context)
        //{
        //    _context = context;
        //}
        public IActionResult Index()
        {
            //return View(await _context.Formations.ToListAsync());
            return View();
        }
    }
}

VitrineCV/Controllers/FormationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VitrineCV.Data;
using VitrineCV.Models;

namespace VitrineCV.Controllers
{
    public class FormationsController : Controller
    {
        private readonly CVContext _context;

        public FormationsController(CVContext context)
        {
            _context = context;
        }

        // GET: Formations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Formations.ToListAsync());
        }

        // GET: Formations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formation = await _context.Formations
                .FirstOrDefaultAsync(m => m.ID == id);
            if (formation == null)
            {
                return NotFound();
            }

            return View(formation);
        }

        // GET: Formations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Formations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Organisme,Intitule,Annee,Ville,Specialisation")] Formation formation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(formation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(formation);
        }

        // GET: Formations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formation = await _context.Formations.FindAsync(id);
            if (formation == null)
            {
                return NotFound();
            }
            return View(formation);
        }

        // POST: Formations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Organisme,Intitule,Annee,Ville,Specialisation")] Formation formation)
        {
            if (id != formation.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(formation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormationExists(formation.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(formation);
        }

        // GET: Formations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formation = await _context.Formations
                .FirstOrDefaultAsync(m => m.ID == id);
            if (formation == null)
            {
                return NotFound();
            }

            return View(formation);
        }

        // POST: Formations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var formation = await _context.Formations.FindAsync(id);
            _context.Formations.Remove(formation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormationExists(int id)
        {
            return _context.Formations.Any(e => e.ID == id);
        }
    }
}

VitrineCV/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VitrineCV.Models;

namespace VitrineCV.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Mon curriculum vitae.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Contact.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VitrineCV/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VitrineCV.Models;

namespace VitrineCV.Controllers
{
    public class PortfolioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult iapoke()
        {
            return View();
        }

        public IActionResult Tetra()
        {
            return View();
        }

        public IActionResult Tictac()
        {
            return View();
        }

        public IActionResult Others()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VitrineCV/Views/CV/Index.cshtml
@model IEnumerable<VitrineCV.Models.Formation>

@{
    ViewData["Title"] = "Curriculum Vitae";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
<span class="cv-img">&nbsp;</span>
<p id="p-pdf">Télécharger le CV en PDF : <br /><a href="/misc/CV.pdf" download="Nicolas_Eisenberg_CV"><i id="pdf" class="fas fa-file-pdf"></i></a></p>
<button class="accordion">Formations</button>
<div class="panel">
    <table class="table tbl-striped tbl-hover">
        <thead>
            <tr>
                <th>
                    Année
                </th>
                <th>
                    Intitulé
                </th>
                <th>
                    Organisme
                </th>
                <th>
                    Ville
                </th>
                <th>
                    Spécialisation
                </th>
            </tr>
        </thead>
        <tbody>
            @*@foreach (var item in Model){
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Annee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Intitule)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Organisme)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ville)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialisation)
            </td>
        </tr>
        }*@
            <tr>
                <td>
                    2019
                </td>
                <td>
                    « Développeur Web/Web mobile » Formation Professionnelle
                </td>
                <td>
                    Elan Formation
                </td>
                <td>
                    Strasbourg
                </td>
                <td>
                    
                </td>
            </tr>
            <tr>
                <td>
                    2016-2017
                </td>
                <td>
                    Première année de cursus Ingénieur (ING1) (Niveau)
                </td>
                <td>
                    EPITA
                </td>
                <td>
                    Le Kremlin-Bicêtre
                </td>
                <td>
                    
                </td>
            </tr>
            <tr>
                <td>
                    2013-2015
                </td>
                <td>
                    CPGE Scientifique
                </td>
                <td>
                    Lycée Kléber
                </td>
                <td>
                    Strasbourg
                </td>
                <td>
                    Physique-Chimie
                </td>
            </tr>
            <tr>
                <td>
                    2010-2011
                </td>
                <td>
                    Baccalauréat Scientifique
                </td>
                <td>
                    Lycée Freppel
                </td>
                <td>
                    Obernai
                </td>
                <td>
                    Mathématiques
                </td>
            </tr>
        </tbody>
    </table>
</div>

<button class="accordion">Compétences</button>
<div class="panel">
    <section>
        <h3>Anglais</h3>
        <p class="cv-p">Courant (TOEIC : 965, passé en 2016)</p>
    </section>
    <section>
        <h3>Langages</h3>
        <h4 class="cv-langages-h">Vus dans un cadre scolaire</h4>
        <ul class="cv-langages-ul">
            <li>C</li>
            <li>C++</li>
            <li>Java</li>
            <li>SH</li>
            <li>PHP</li>
            <li>HTML</li>
            <li>CSS</li>
            <li>SQL</li>
            <li>Git</li>
            <li>Unix</li>
        </ul>
        <h4 class="cv-langages-h">Vus en auto-didacte</h4>
        <ul class="cv-langages-ul">
            <li>C#</li>
            <li>.NET</li>
            <li>Ruby</li>
            <li>Bootstrap</li>
            <li>Et plus à venir</li>
        </ul>
    </section>
</div>

<button class="accordion">Parcours</button>
<div class="panel">
    <section>
        <p class="cv-p" id="cv-p-margin-top">
            Après deux années de classes préparatoires aux grandes écoles au Lycée Kléber de Strasbourg, j’ai choisi de m’orienter vers le secteur
            informatique et d’intégrer une école d’ingénieur de la région parisienne, dans le domaine du numérique, EPITA.</p>
        <p class="cv-p">
            Cette expérience m’a conforté dans mon choix d’orientation et m’a permis d’acquérir des compétences dans ce domaine. J’ai pu y
            apprendre le C, C++, Java et SH en profondeur à travers divers projets sur des périodes courtes, qui m’ont ainsi appris à travailler
            avec une deadline stricte et de manière rigoureuse. J’ai intégré cette formation pour étendre mes connaissances et poursuivre ce projet,
            par exemple pour une poursuite d’études en alternance.
        </p>
    </section>
</div>

<button class="accordion">Extras sur moi</button>
<div class="panel">
    <section>
        <h3>Loisirs</h3>
        <p class="cv-p">
            Mis à part les jeux-vidéos, que j'ai souvent pratiqué de manière compétitive, mon loisir principal pendant des années a été la <em>guitare</em>.
            J'ai pratiqué cet instrument pendant environ une dizaine d'années, principalement seul mais pas que. J'ai notamment joué à la fête de la musique de Schirmeck
            l'année de mon bac. C'était une expérience intéressante et qui, avec le recul, m'a pas mal appris à faire confiance dans un travail d'équipe.
        </p>
        <p class="cv-p">
            Autrement, une grande partie de mon temps libre est passé à se renseigner sur un tas de sujet. J'aime essayer beaucoup de choses et me renseigner sur celles-ci.
            C'est d'ailleurs en partie ce qui me plaît dans le numérique : il y a moult domaines qui sont différents mais reposent tous sur un socle commun.
        </p>
        <h3>Expérience notable</h3>
        <p class="cv-p">
            J'ai fait partie de l'équipe de rédaction de certains sites liées à des associations du milieu e-sportif. Notamment aAa en tant que rédacteur Starcraft 2, puis
            League of Legends, j'ai également fait de la rédaction tous jeux pour Eclypsia pendant un mois et enfin pour GamersOrigin pour Hearthstone avant de devoir arrêter
            par manque cruel de temps durant ma première année à EPITA.
        </p>
    </section>
</div>

VitrineCV/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>

<address>
    Nicolas EISENBERG<br />
    42 rue Gounod<br />
    67400 ILLKIRCH<br />
    <abbr title="(+33)">Tel: 07.60.36.98.65</abbr>
</address>

<address>
    <strong>Support:</strong> <a href="mailto:eisenberg.nicolas@gmail.com">eisenberg.nicolas@gmail.com</a>
</address>

VitrineCV/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Accueil";
}

<h2>Bienvenue sur mon site CV</h2>

<article class="p-accueil">
    <h3>A propos du site</h3>
    <p>Ayant débuté mi-mai 2019 une formation professionnelle de Développement Web qui nécessite un stage, j'ai décidé fin-mai de développer ce site. D'une part pour avoir un projet concret en ASP.NET que j'apprécie beaucoup. D'autre part car il me semble qu'un site est la meilleure vitrine possible pour un développeur web qui cherche un stage ; d'autant plus que décrire des projets dans un CV est bien, pouvoir en voir la substance est mieux.</p>
</article>

<h3 class="h-accueil">Recherche</h3>
<section class="recherche">Je suis actuellement à la recherche d'un stage en Développement Web</section>
<article class="p-accueil">
    <p>Ce stage a pour but de réaliser un livrable ou une partie d'un livrable dans le domaine du Web, de préférence en back-end, afin de passer l'examen du titre professionnel RNCP de niveau III (Bac +2) « Développeur Web/Web Mobile »</p>
    Le détail du REAC (Référentiel Emploi Activités Compétences) est disponible <a class="reac-link" target="_blank" href="https://www.banque.di.afpa.fr/EspaceEmployeursCandidatsActeurs/EGPResultat.aspx?ct=01280m03&type=t">à cette adresse</a>. Il contient notamment la grille de compétence suivante :
</article>
    
<img class="img-reac" src="~/images/reac.jpg" alt="grille compétences" />

<article class="p-accueil">
    <p>A l'issue de ce stage je souhaiterais prolonger mon expérience par un contrat de professionnalisation pour un titre de niveau II (Bac +4).
</article>

VitrineCV/Views/Portfolio/Index.cshtml
@{
    ViewData["Title"] = "View";
}

<h2>Projets Réalisés</h2>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/pkmnbanner.jpg" alt="iapoke" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p class="blackme">
                    IA Pokémon<br />
                    <a class="btn btn-default" asp-area="" asp-controller="Portfolio" asp-action="iapoke">
                        Voir plus
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/tetra.jpg" alt="Tetravex" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    N-Résolveur de Tétravex.<br />
                    <a class="btn btn-default" asp-area="" asp-controller="Portfolio" asp-action="Tetra">
                        Voir plus
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/vibes.jpg" alt="Vibes Theme" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p class="blackme">
                    Reproduction de thême WordPress<br />
                    <a target="_blank" class="btn btn-default" href="~/misc/index.html">
                        Voir plus
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/tictac.jpg" alt="Tictactoe" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Morpion dynamique<br />
                    <a class="btn btn-default" asp-area="" asp-controller="Portfolio" asp-action="Tictac">
                        Voir plus
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/autres.jpg" alt="autres" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Et d'autres encores...<br />
                    <a class="btn btn-default" asp-area="" asp-controller="Portfolio" asp-action="Others">
                        Voir plus
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

VitrineCV/Views/Portfolio/Others.cshtml
@{
    ViewData["Title"] = "Others";
}

<h2>Autres projets entrepris</h2>

<p>
    Que ce soit parce que je ne possède plus le code source de certains projets ou par choix de pertinence, je n'ai fait des Views pour chaque projet que j'ai fait, en voici une liste non exhaustive d'autres applications notables sur lesquelles j'ai travaillé.
</p>

<h3>C</h3>
<h4 class="ot-h">Lecteur ISO</h4>
<p class="ot-p">Un binaire permettant de naviguer dans le contenu d'un fichier ISO passé en paramètre. Un prompt apparaissait pour entrer diverses commandes comme CD pour se déplacer dans les directories (en prenant '.' et '..' comme possibilités, CAT pour afficher le contenu d'un sous fichier, LS pour afficher une liste des fichiers et répertoires présents à un endroit précis...</p>
<h4 class="ot-h">Parseur de Shell</h4>
<p class="ot-p">Pour le début d'un projet de Terminal (type Bash) j'ai implémenté une grande partie d'un parseur de langage Shell.</p>

<h3>C++</h3>
<p class="ot-p">Je m'étais également penché sur le projet frère de l'IA pokémon qui consistait à implémenter un algorithme de Pathfinding pour aller d'un point A à un point B en ayant des cases possédant divers attributs. Par exemple une case avec de l'eau ou une case forêt "coûtait" plus de points de mouvement qu'une case plaine.</p>

<h3><i class="fab fa-java"></i> JAVA</h3>
<p class="ot-p">Implémentation des classes nécessaires à une bataille navale en ligne. En particulier écrire les classes des différents bateaux, de la grille, des méthodes nécessaires à indiquer qu'un bateau est coulé et le transmettre au serveur 
    avec un .json.</p>

<h3>Ruby/Rails</h3>
<p class="ot-p">Simple initiation au langage à travers un tutorial sur le net. Il m'a appris néanmoins la notion de MVC, réutilisée notamment dans le projet du site web CV.</p>

<h3><i class="fab fa-windows"></i> ASP.NET/C#</h3>
<p class="ot-p">Ce site est un projet en ASP.NET / C# sur la base du template de Visual Studio Community. La partie Formations du CV a été conçue à la base grâce à une base de données, bien que peu utile dans ce cas précis, ça m'a permis de voir les appels de BDD sur une page Razor. Cependant pour une facilité d'hébergement j'ai repassé le code en statique.</p>

VitrineCV/Views/Portfolio/Tetra.cshtml
@{
    ViewData["Title"] = "Tetra";
}

<h2>N-solver de Tetravex</h2>

<section>
    <p>Un tétravex est un ensemble de tuiles qui portent chacune un nombre sur chacuns de leurs côtés. Ce sont par exemple des dominos à 4 faces.</p>
    <p>
        Le N problème est de savoir, avec un ensemble de tuiles, si il existe une ou plusieurs solutions pour que chaque faces voisines aient le même nombre, et évidemment de savoir
        quelles sont ces solutions. Cette application cherche ces solutions à l'aide d'un algorithme appelé Breadth-first Search (BFS), qui va exploré des arbres de solutions pour résoudre
        le problème. Dès qu'une solution est trouvée elle est gardée.
    </p>
</section>

<section><h3 class="project-name"><i class="fab fa-github"></i><a href="https://github.com/Aranaevens/tetra-solver">  Application entière sur GitHub  </a><i class="fab fa-github"></i></h3></section>

<script src="https://gist.github.com/Aranaevens/2a85efd792058cf35bcc72feeaec2999.js"></script>

VitrineCV/Views/Portfolio/Tictac.cshtml
@{
    ViewData["Title"] = "Tictac";
}

<h2>TicTacToe (Morpion) Dynamique</h2>

<section>
    <p>Le but de ce projet était simplement de faire un Morpion pour jouer sur un Wamp local en PHP.</p>
    <p>
        Chaque joueur peut rentrer son nom et le symbole de son choix dans un formulaire brut. La page est ensuite redirigée vers le morpion en lui même.
        Trois zones sont définies avec Bootstrap : la grille de jeu et une zone par joueur, récapitulant le symbole et le tour du joueur en cours. Chaque fois
        que l'on clique sur une case vide de la grille, le symbole du joueur courant est affiché dans la case, la main passe à l'autre joueur. L'ensemble des données
        nécessaires sont passées soit par session (pour le tableau entier, qui est une classe ayant un attribut matrice (array d'array)) soit par Get pour retrouver
        les coordonnées du clic.
    </p>
    <p>Dès que l'application détecte un vainqueur, le jeu se gèle, le vainqueur est affiché clairement et un bouton pour rejouer est affiché.</p>
</section>

<section><h3 class="project-name"><i class="fab fa-github"></i><a href="https://github.com/Aranaevens/Tictactoe">  Application entière sur GitHub  </a><i class="fab fa-github"></i></h3></section>

<script src="https://gist.github.com/Aranaevens/76373bcff588b2e780967b5a3ce387b8.js"></script>

VitrineCV/Views/Portfolio/iapoke.cshtml
@{
    ViewData["Title"] = "iapoke";
}

<h2>IA de Bataille Pokémon</h2>

<section>
    <p>Le but de ce projet était d'automatiser un combat entre deux dresseurs de Pokémon.</p>
    <p>Chaque dresseur commençait avec une équipe de Pokémons, possédant des attaques avec chacunes des attributs. La liste des pokémons, des attaques et des statistiques
    sont récupérés et parsés à partir de fichiers CSV. Ensuite, une fonction d'évaluation vient rendre compte de l'état de la partie. Cette fonction d'évaluation sert à
    l'algorithme Minmax pour choisir quelle attaque faire chaque tour.</p>
    <p>L'application récupère les choix sur le serveur et applique les différentes attaques utilisées et boucle jusqu'à la défaite d'un des deux participants.</p>
</section>

<section><h3 class="project-name"><i class="fab fa-github"></i><a href="http://https://github.com/Aranaevens/iapoke">  Application entière sur GitHub  </a><i class="fab fa-github"></i></h3></section>

<script src="https://gist.github.com/Aranaevens/3c9e83e52e2ca5e6c72ee9fc94f2adf6.js"></script>

VitrineCV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nicolas E</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/mylogo.jpg" alt="Nicolas EISENBERG" style="width:50px;height:50px;" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Accueil</a></li>
                    <li><a asp-area="" asp-controller="CV" asp-action="Index">CV</a></li>
                    <li><a asp-area="" asp-controller="Portfolio" asp-action="Index">Portfolio</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <main class="container body-content">
        @RenderBody()
    </main>
    <footer class="container">
        <hr />
        <p>&copy; 2019 - Nicolas EISENBERG</p>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>